FROM python:3.11

WORKDIR /src

COPY requirements.txt .

# Upgrade pip before installing dependencies
RUN pip install --upgrade pip && \
    pip install  -r requirements.txt 
#--no-cache-dir

COPY app ./app

COPY .env /src/.env

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]